name: Generate Documentation

# Run GH actions manually: https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
on: workflow_dispatch
  
jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install Requirements
      run: brew install doxygen
        && brew install sphinx-doc
        && pip3 install sphinx-rtd-theme
        && pip3 install breathe
        && pip3 install sphinx-sitemap
    - name: Checkout Repo
      uses: actions/checkout@1.0.0
    - name: Build Docs
      run: cd docs
        && make html
        && cd temp_build/html
        && touch .nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/temp_build/html # The folder the action should deploy.
